Add Qt/QML sample
brizental/glean.js pull request #2
Opened 2020-11-10 10:56 UTC by brizental

2020-11-10 15:14 UTC, Dexterp37 requested changes

2020-11-10 15:45 UTC, brizental commented on samples/web-app-static/README.md
> +1. Build Glean.js for the browser.
> I believe this is for web applications, right? 

Nope, I learned about [UMD](https://github.com/umdjs/umd) on my last PR, and [use it](https://github.com/brizental/glean.js/blob/main/webpack.config.browser.js#L28) now on our browser build. **tl;dr;** It allows us to build one Glean.js that can be used by static websites, web apps using webpack or any other bundling tool and web extensions (unless webextensions need other special treatment).

So when I say browser here, I mean browser the environment, regardless of the type of application that is using it.

2020-11-10 18:10 UTC, Dexterp37 commented on samples/web-app-static/README.md
> +1. Build Glean.js for the browser.
Does it mean that you're allowed to use addon-specific APIs and that it will polyfill accordingly? Or how does that work?

2020-11-11 08:11 UTC, brizental commented on samples/web-app-static/README.md
> +1. Build Glean.js for the browser.
Same as I commented in https://github.com/brizental/glean.js/pull/3#discussion_r521183754 :)

2020-11-11 09:48 UTC, Dexterp37 approved these changes

2020-11-11 10:10 UTC, merged