Bug 1676143 - Add web extension sample
brizental/glean.js pull request #3
Opened 2020-11-10 15:09 UTC by brizental

BONUS: housekeeping.

2020-11-10 15:22 UTC, Dexterp37 commented on samples/web-extension/README.md
> +1. Build Glean.js for the browser. On the root folder of this repository run:
Can you clarify what "browser" means here?

2020-11-10 15:22 UTC, Dexterp37 commented on samples/web-extension/package.json
> +  "main": "index.js",
Do we need really webpack for this example?

2020-11-10 15:41 UTC, brizental commented on samples/web-extension/README.md
> +1. Build Glean.js for the browser. On the root folder of this repository run:
Browser here means the environment. Regardless if it is a webextension or a a web app static or other.

2020-11-10 15:42 UTC, brizental commented on samples/web-extension/package.json
> +  "main": "index.js",
It's more straight forward than vendoring the Glean.js script, IMO.

2020-11-10 18:11 UTC, Dexterp37 commented on samples/web-extension/README.md
> +1. Build Glean.js for the browser. On the root folder of this repository run:
Web extensions are allowed to use different APIs than webpages. Who's responsible for checking what's used where?

2020-11-10 18:13 UTC, Dexterp37 commented on samples/web-extension/package.json
> +  "main": "index.js",
Got it. This is needed because webextensions can only include files that are stored as children of the directory where the manifest file is. So we either copy the glean distribution here as a pre-build step, or use a bundler.

Any chance you could squeeze this explanation in the README?

2020-11-10 18:13 UTC, Dexterp37 commented on samples/web-extension/README.md
> +  - **Chrome**
```suggestion
  - **Chromium-based browsers**
```

2020-11-11 08:09 UTC, brizental commented on samples/web-extension/README.md
> +1. Build Glean.js for the browser. On the root folder of this repository run:
Yes, you are right about that. For now though, it hasn't been necessary to split the build between web extension and web apps, so I propose we cross that bridge when we get there.

2020-11-11 08:35 UTC, Dexterp37 requested changes

2020-11-11 08:35 UTC, Dexterp37 commented on samples/web-extension/README.md
> +1. Build Glean.js for the browser. On the root folder of this repository run:
While we could tackle this going forward, since we already know APIs will differ, I believe we're better suited to change and clarify our comments while our codebase is small, setting the right track for others to understand if they want to contribute as well

2020-11-11 08:35 UTC, Dexterp37 commented on samples/web-extension/package.json
> +  "main": "index.js",
I think this is still missing

2020-11-11 08:38 UTC, brizental commented on samples/web-extension/package.json
> +  "main": "index.js",
I added a small note on the README.md https://github.com/brizental/glean.js/pull/3/commits/e43f97282e74546b9b73bb002483e622a4e69119, let me know if you think it is not enough.

2020-11-11 08:40 UTC, Dexterp37 commented on samples/web-extension/package.json
> +  "main": "index.js",
It doesn't explain _why_ we're doing that (the reason that I talked about 2 comments above)

2020-11-11 09:11 UTC, brizental commented on samples/web-extension/package.json
> +  "main": "index.js",
Ah, I see. Let me add that :)

2020-11-11 09:12 UTC, brizental commented on samples/web-extension/README.md
> +1. Build Glean.js for the browser. On the root folder of this repository run:
My point in thinking it's best that we only bifurcate these build configurations when we need to, is related to the fact that I am not even sure we are going to need to.

On the proof of concept we did not see the need for two different builds for websites and web extensions and in fact the only moment we needed to use specific web extensions APIs was [when getting the application id](https://github.com/brizental/gleanjs/blob/main/src/glean.js#L16-L17), which now we have the user pass explicitly through the `initialize` function, making even that use case unnecessary.

I thought maybe to get platform information we'd need different logic, but web extensions, i just verified, have access to the `navigator.userAgent` property, so they can share code with websites in this regard too.

2020-11-11 09:44 UTC, Dexterp37 approved these changes

2020-11-11 09:44 UTC, Dexterp37 commented on samples/web-extension/README.md
> +1. Build Glean.js for the browser. On the root folder of this repository run:
All right,let's stick to the current naming and change this if it becomes confusing to others in the future.

2020-11-11 10:09 UTC, merged